name: taskly
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  calendar_view: ^1.0.2
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  sqflite: ^2.2.4
  path: ^1.8.2
  flutter_colorpicker: ^1.0.3
  flutter_multi_select_items: ^0.4.2
  intl: ^0.18.0
  quill_html_editor: ^2.0.7
  floor: ^1.4.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.11.0"

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Inter
      fonts:

        - asset: assets/fonts/Inter.ttf
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21