import 'dart:math';

import 'package:uuid/uuid.dart';

DateTime generateRandomTime() {
  final random = Random();
  final now = DateTime.now();

  final hours =
      random.nextInt(11) - 5; // Generates a random number between -5 and 5
  final time = now.add(Duration(hours: hours));
  return time;
}

List<Map<String, dynamic>> dummyTasks = [
  {
    'id': Uuid().v4().toString(),
    'title': 'Attend daily standup meeting',
    'rich_description': '<p>Discuss progress and blockers with the team</p>',
    'createdAt': DateTime(2023, 2, 25, 9, 0),
    'beginAt': null,
    'endAt': null,
    'repeat': false,
    'priority': 1,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Complete coding tasks',
    'rich_description': '<p>Finish coding tasks assigned for the day</p>',
    'createdAt': DateTime(2023, 3, 1, 10, 0),
    'beginAt': null,
    'endAt': null,
    'repeat': false,
    'priority': 2,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Take a lunch break',
    'rich_description': '<p>Have a healthy and energizing meal</p>',
    'createdAt': DateTime(2023, 2, 19, 12, 0),
    'beginAt': null,
    'endAt': null,
    'repeat': false,
    'priority': 3,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Attend a meeting',
    'rich_description': '<p>Discuss project details with clients</p>',
    'createdAt': DateTime.now(),
    'beginAt': null,
    'endAt': null,
    'repeat': false,
    'priority': 4,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Study for a certification',
    'rich_description': '<p>Spend at least an hour reading study materials</p>',
    'createdAt': DateTime.now(),
    'beginAt': DateTime.now(),
    'endAt': DateTime.now().add(Duration(hours: 1)),
    'repeat': false,
    'priority': 5,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Pick up groceries',
    'rich_description': '<p>Buy ingredients for dinner</p>',
    'createdAt': DateTime(2023, 2, 25, 18, 0),
    'beginAt': null,
    'endAt': null,
    'repeat': false,
    'priority': 6,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Cook dinner',
    'rich_description': '<p>Prepare and cook a healthy meal</p>',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 19, 0),
    'endAt': DateTime(2023, 2, 19, 20, 0),
    'repeat': false,
    'priority': 7,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Read a book',
  //   'rich_description': '<p>Spend time reading a book of your choice</p>',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 19, 21, 0),
  //   'endAt': DateTime(2023, 2, 19, 22, 0),
  //   'repeat': false,
  //   'priority': 8,
  //   'isCompleted': false,
  //   'projectId': 'entertainment',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Meditate',
  //   'rich_description': '<p>Spend some time meditating and relaxing</p>',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 19, 22, 0),
  //   'endAt': DateTime(2023, 2, 19, 22, 30),
  //   'repeat': false,
  //   'priority': 9,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString()',
  //   'title': 'Go to bed',
  //   'rich_description': '<p>Get a good night\'s sleep to prepare for tomorrow</p>',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 19, 23, 0),
  //   'endAt': DateTime(2023, 2, 20, 7, 0),
  //   'repeat': false,
  //   'priority': 10,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true,
  // },
];

List<Map<String, dynamic>> anotherDummyTasks = [
  {
    'id': Uuid().v4().toString(),
    'title': 'Prepare for project meeting',
    'rich_description':
        '<p>Review project goals, prepare slides and talking points for team meeting</p>',
    'createdAt': DateTime(2023, 2, 20, 8, 0),
    'beginAt': DateTime(2023, 2, 20, 8, 0),
    'endAt': DateTime(2023, 2, 20, 8, 0),
    'repeat': false,
    'priority': 10,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': Uuid().v4().toString(),
    'title': 'Attend project meeting',
    'rich_description':
        '<p>Participate in project meeting, provide updates and discuss any issues</p>',
    'createdAt': DateTime(2023, 2, 20, 10, 0),
    'beginAt': DateTime(2023, 2, 20, 10, 0),
    'endAt': null,
    'repeat': false,
    'priority': 2,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Reply to important emails',
  //   'rich_description':
  //       'Check email and respond to important messages from clients and team members',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 11, 0),
  //   'endAt': DateTime(2023, 2, 20, 12, 0),
  //   'repeat': false,
  //   'priority': 3,
  //   'isCompleted': false,
  //   'projectId': 'work',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Lunch break',
  //   'rich_description': '<p>Take a break to eat and recharge</p>',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 12, 0),
  //   'endAt': DateTime(2023, 2, 20, 13, 0),
  //   'repeat': false,
  //   'priority': 4,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Attend team brainstorming session',
  //   'rich_description':
  //       'Participate in a brainstorming session with team members to generate new ideas for a project',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 13, 0),
  //   'endAt': DateTime(2023, 2, 20, 14, 0),
  //   'repeat': false,
  //   'priority': 5,
  //   'isCompleted': false,
  //   'projectId': 'work',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Gym workout',
  //   'rich_description':
  //       'Hit the gym for a workout session to maintain good health',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 15, 0),
  //   'endAt': DateTime(2023, 2, 20, 16, 0),
  //   'repeat': false,
  //   'priority': 6,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Read a chapter of a book',
  //   'rich_description':
  //       'Spend some time reading a chapter of a book to gain knowledge and unwind',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 17, 0),
  //   'endAt': DateTime(2023, 2, 20, 17, 30),
  //   'repeat': false,
  //   'priority': 7,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Prepare dinner',
  //   'rich_description': '<p>Plan and prepare a healthy dinner for oneself</p>',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 18, 0),
  //   'endAt': DateTime(2023, 2, 20, 19, 0),
  //   'repeat': false,
  //   'priority': 8,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString(),
  //   'title': 'Watch a movie',
  //   'rich_description': '<p>Relax by watching a movie or TV show</p>',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 20, 0),
  //   'endAt': DateTime(2023, 2, 20, 22, 0),
  //   'repeat': false,
  //   'priority': 9,
  //   'isCompleted': false,
  //   'projectId': 'entertainment',
  //   'isVisible': true,
  // },
  // {
  //   'id': Uuid().v4().toString()',
  //   'title': 'Prepare for the next day',
  //   'rich_description':
  //       'Check calendar and to-do list, plan out tasks for the next day',
  //   'createdAt': DateTime.now(),
  //   'beginAt': DateTime(2023, 2, 20, 22, 0),
  //   'endAt': DateTime(2023, 2, 20, 23, 0),
  //   'repeat': false,
  //   'priority': 10,
  //   'isCompleted': false,
  //   'projectId': 'personal',
  //   'isVisible': true,
  // },
];

final List dummyTags = [
  'All',
  'In Progress',
  'Completed',
  'Todo',
];
final List<String> dummyUserTags = <String>[
  'Custom tags',
  'Personal',
  'Work',
  'Shopping'
];
