import 'dart:math';

import 'package:flutter/material.dart';

DateTime generateRandomTime() {
  final random = Random();
  final now = DateTime.now();

  final hours =
      random.nextInt(11) - 5; // Generates a random number between -5 and 5
  final time = now.add(Duration(hours: hours));
  return time;
}

final List<Map<String, dynamic>> dummyTasks = [
  {
    'id': '1',
    'title': 'Attend daily standup meeting',
    'rich_description': 'Discuss progress and blockers with the team',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 9, 0),
    'endAt': DateTime(2023, 2, 19, 9, 30),
    'repeat': false,
    'priority': 1,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '2',
    'title': 'Complete coding tasks',
    'rich_description': 'Finish coding tasks assigned for the day',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 10, 0),
    'endAt': DateTime(2023, 2, 19, 12, 0),
    'repeat': false,
    'priority': 2,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '3',
    'title': 'Take a lunch break',
    'rich_description': 'Have a healthy and energizing meal',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 12, 0),
    'endAt': DateTime(2023, 2, 19, 13, 0),
    'repeat': false,
    'priority': 3,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '4',
    'title': 'Attend a meeting',
    'rich_description': 'Discuss project details with clients',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 14, 0),
    'endAt': DateTime(2023, 2, 19, 15, 0),
    'repeat': false,
    'priority': 4,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '5',
    'title': 'Study for a certification',
    'rich_description': 'Spend at least an hour reading study materials',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 16, 0),
    'endAt': DateTime(2023, 2, 19, 17, 0),
    'repeat': false,
    'priority': 5,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '6',
    'title': 'Pick up groceries',
    'rich_description': 'Buy ingredients for dinner',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 18, 0),
    'endAt': DateTime(2023, 2, 19, 19, 0),
    'repeat': false,
    'priority': 6,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '7',
    'title': 'Cook dinner',
    'rich_description': 'Prepare and cook a healthy meal',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 19, 0),
    'endAt': DateTime(2023, 2, 19, 20, 0),
    'repeat': false,
    'priority': 7,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '8',
    'title': 'Read a book',
    'rich_description': 'Spend time reading a book of your choice',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 21, 0),
    'endAt': DateTime(2023, 2, 19, 22, 0),
    'repeat': false,
    'priority': 8,
    'isCompleted': false,
    'projectId': 'entertainment',
    'isVisible': true,
  },
  {
    'id': '9',
    'title': 'Meditate',
    'rich_description': 'Spend some time meditating and relaxing',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 22, 0),
    'endAt': DateTime(2023, 2, 19, 22, 30),
    'repeat': false,
    'priority': 9,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '10',
    'title': 'Go to bed',
    'rich_description': 'Get a good night\'s sleep to prepare for tomorrow',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 19, 23, 0),
    'endAt': DateTime(2023, 2, 20, 7, 0),
    'repeat': false,
    'priority': 10,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
];

final List<Map<String, dynamic>> anotherDummyTasks = [
  {
    'id': '1',
    'title': 'Prepare for project meeting',
    'rich_description':
        'Review project goals, prepare slides and talking points for team meeting',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 8, 0),
    'endAt': DateTime(2023, 2, 20, 10, 0),
    'repeat': false,
    'priority': 10,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '2',
    'title': 'Attend project meeting',
    'rich_description':
        'Participate in project meeting, provide updates and discuss any issues',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 10, 0),
    'endAt': DateTime(2023, 2, 20, 11, 0),
    'repeat': false,
    'priority': 2,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '3',
    'title': 'Reply to important emails',
    'rich_description':
        'Check email and respond to important messages from clients and team members',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 11, 0),
    'endAt': DateTime(2023, 2, 20, 12, 0),
    'repeat': false,
    'priority': 3,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '4',
    'title': 'Lunch break',
    'rich_description': 'Take a break to eat and recharge',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 12, 0),
    'endAt': DateTime(2023, 2, 20, 13, 0),
    'repeat': false,
    'priority': 4,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '5',
    'title': 'Attend team brainstorming session',
    'rich_description':
        'Participate in a brainstorming session with team members to generate new ideas for a project',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 13, 0),
    'endAt': DateTime(2023, 2, 20, 14, 0),
    'repeat': false,
    'priority': 5,
    'isCompleted': false,
    'projectId': 'work',
    'isVisible': true,
  },
  {
    'id': '6',
    'title': 'Gym workout',
    'rich_description':
        'Hit the gym for a workout session to maintain good health',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 15, 0),
    'endAt': DateTime(2023, 2, 20, 16, 0),
    'repeat': false,
    'priority': 6,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true
  },
  {
    'id': '7',
    'title': 'Read a chapter of a book',
    'rich_description':
        'Spend some time reading a chapter of a book to gain knowledge and unwind',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 17, 0),
    'endAt': DateTime(2023, 2, 20, 17, 30),
    'repeat': false,
    'priority': 7,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '8',
    'title': 'Prepare dinner',
    'rich_description': 'Plan and prepare a healthy dinner for oneself',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 18, 0),
    'endAt': DateTime(2023, 2, 20, 19, 0),
    'repeat': false,
    'priority': 8,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
  {
    'id': '9',
    'title': 'Watch a movie',
    'rich_description': 'Relax by watching a movie or TV show',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 20, 0),
    'endAt': DateTime(2023, 2, 20, 22, 0),
    'repeat': false,
    'priority': 9,
    'isCompleted': false,
    'projectId': 'entertainment',
    'isVisible': true,
  },
  {
    'id': '10',
    'title': 'Prepare for the next day',
    'rich_description':
        'Check calendar and to-do list, plan out tasks for the next day',
    'createdAt': DateTime.now(),
    'beginAt': DateTime(2023, 2, 20, 22, 0),
    'endAt': DateTime(2023, 2, 20, 23, 0),
    'repeat': false,
    'priority': 10,
    'isCompleted': false,
    'projectId': 'personal',
    'isVisible': true,
  },
];

final List dummyTags = [
  'All',
  'In Progress',
  'Completed',
  'Todo',
];
final List<String> dummyUserTags = <String>[
  'Custom tags',
  'Personal',
  'Work',
  'Shopping'
];
